### ISSUE TITLE
Inconsistent Image Display

### ISSUE THREAD

**Issue by chenneman-usbp** [Esri/storymap-shortlist#62]
I am experiencing an issue with inconsistent image display in the shortlist app.  The images all display in my web map, but when opened in the shortlist app, some of them show broken links.  When I reload the layer to the web map and open it again in shortlist, the broken links have changed.  Any suggestions?

**Comment by RupertEssinger** [comment]
Hi. I don't think I've seen that before. Do those image URLs work OK in your web browser if you just paste them in outside the Shortlist. Can you share the URLs to the web map and the Shortlist? Thanks

(For questions I'd recommend posting on the Story Maps Community Forum:
https://geonet.esri.com/community/gis/web-gis/storymaps/overview
because that gives you access to a larger pool of people including story map authors who may have seen the issue, and also enables the whole  user community to see the answers.- Rupert)
